//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizDuel.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizDuel.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string BirthdateLabel {
            get {
                return ResourceManager.GetString("BirthdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать игру.
        /// </summary>
        internal static string CreateGameButton {
            get {
                return ResourceManager.GetString("CreateGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать игру.
        /// </summary>
        internal static string Game_CreateError {
            get {
                return ResourceManager.GetString("Game.CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра уже закончилась..
        /// </summary>
        internal static string Game_Finished {
            get {
                return ResourceManager.GetString("Game.Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра не найдена.
        /// </summary>
        internal static string Game_IsNotFound {
            get {
                return ResourceManager.GetString("Game.IsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться.
        /// </summary>
        internal static string Game_JoinButton {
            get {
                return ResourceManager.GetString("Game.JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка подключения к игре.
        /// </summary>
        internal static string Game_JoinError {
            get {
                return ResourceManager.GetString("Game.JoinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при загрузке категорий.
        /// </summary>
        internal static string Game_LoadCategoryError {
            get {
                return ResourceManager.GetString("Game.LoadCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Второй игрок еще не присоединился..
        /// </summary>
        internal static string Game_NotStarted {
            get {
                return ResourceManager.GetString("Game.NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете подключиться к своей игре.
        /// </summary>
        internal static string Game_SamePlayers {
            get {
                return ResourceManager.GetString("Game.SamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите категорию.
        /// </summary>
        internal static string Game_SelectCategory {
            get {
                return ResourceManager.GetString("Game.SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться к игре..
        /// </summary>
        internal static string Game_StateError {
            get {
                return ResourceManager.GetString("Game.StateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить игры.
        /// </summary>
        internal static string Join_UpdateError {
            get {
                return ResourceManager.GetString("Join.UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Join_UpdateGames {
            get {
                return ResourceManager.GetString("Join.UpdateGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться к игре.
        /// </summary>
        internal static string JoinGameButton {
            get {
                return ResourceManager.GetString("JoinGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Login_BtnLogin {
            get {
                return ResourceManager.GetString("Login.BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните имя пользователя.
        /// </summary>
        internal static string Login_EmptyUsername {
            get {
                return ResourceManager.GetString("Login.EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при входе в аккаунт.
        /// </summary>
        internal static string Login_Error {
            get {
                return ResourceManager.GetString("Login.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта? .
        /// </summary>
        internal static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login.NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого пользователя не существует.
        /// </summary>
        internal static string Login_NonExistingUser {
            get {
                return ResourceManager.GetString("Login.NonExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешный вход в аккаунт.
        /// </summary>
        internal static string Login_Success {
            get {
                return ResourceManager.GetString("Login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль.
        /// </summary>
        internal static string Login_WrongPassword {
            get {
                return ResourceManager.GetString("Login.WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об ошибке.
        /// </summary>
        internal static string Notification_Error {
            get {
                return ResourceManager.GetString("Notification.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная операция.
        /// </summary>
        internal static string Notification_Success {
            get {
                return ResourceManager.GetString("Notification.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну строчную букву.
        /// </summary>
        internal static string Password_HasLowerChar {
            get {
                return ResourceManager.GetString("Password.HasLowerChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну цифру.
        /// </summary>
        internal static string Password_HasNumber {
            get {
                return ResourceManager.GetString("Password.HasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы один специальный символ.
        /// </summary>
        internal static string Password_HasSymbols {
            get {
                return ResourceManager.GetString("Password.HasSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну заглавную букву.
        /// </summary>
        internal static string Password_HasUpperChar {
            get {
                return ResourceManager.GetString("Password.HasUpperChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать только латинские буквы.
        /// </summary>
        internal static string Password_IsLatinOnly {
            get {
                return ResourceManager.GetString("Password.IsLatinOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 8 и не более 20 символов.
        /// </summary>
        internal static string Password_MinMaxChar {
            get {
                return ResourceManager.GetString("Password.MinMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок 1.
        /// </summary>
        internal static string Player1Label {
            get {
                return ResourceManager.GetString("Player1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок 2 .
        /// </summary>
        internal static string Player2Label {
            get {
                return ResourceManager.GetString("Player2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string Register_EmptyPassword {
            get {
                return ResourceManager.GetString("Register.EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите повторный пароль.
        /// </summary>
        internal static string Register_EmptyRepeatPassword {
            get {
                return ResourceManager.GetString("Register.EmptyRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя.
        /// </summary>
        internal static string Register_EmptyUsername {
            get {
                return ResourceManager.GetString("Register.EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при регистрации аккаунта.
        /// </summary>
        internal static string Register_Error {
            get {
                return ResourceManager.GetString("Register.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой пользователь уже существует..
        /// </summary>
        internal static string Register_ExistingUser {
            get {
                return ResourceManager.GetString("Register.ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть аккаунт?.
        /// </summary>
        internal static string Register_HaveAnAccount {
            get {
                return ResourceManager.GetString("Register.HaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам должно быть не меньше 4 лет.
        /// </summary>
        internal static string Register_InvalidAge {
            get {
                return ResourceManager.GetString("Register.InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        internal static string Register_InvalidRepeatPassword {
            get {
                return ResourceManager.GetString("Register.InvalidRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно.
        /// </summary>
        internal static string Register_Successful {
            get {
                return ResourceManager.GetString("Register.Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        internal static string RepeatPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
    }
}
