version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: quizduel_postgres
    restart: always
    environment:
      POSTGRES_USER: salavat
      POSTGRES_PASSWORD: salavat
      POSTGRES_DB: quizduel
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
